variables:
  buildConfiguration: Release

pool:
  vmImage: 'ubuntu-18.04' 

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Dictator/Dictator.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    arguments: '--configuration $(BuildConfiguration) --collect "XPlat Code coverage"'
    projects: 'Dictator_Tests/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Install ReportGenerator Global Tool
  inputs:
      command: custom
      custom: tool
      arguments: install dotnet-reportgenerator-globaltool -g

- script: 
    echo "##vso[task.prependpath]$HOME/.dotnet/tools"

- script: 
    reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"'


- task: PublishCodeCoverageResults@1  
  displayName: 'Publish code coverage'  
  inputs:  
    codeCoverageTool: Cobertura  
    summaryFileLocation: '$(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml'  

