variables:
  buildConfiguration: Release

pool:
  vmImage: 'ubuntu-18.04' 

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Dictator/Dictator.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Running code coverage'
  inputs: 
      command: test
      projects: 'Dictator_Tests/*_Tests.csproj'
      arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/CodeCoverage'


- task: DotNetCoreCLI@2
  displayName: Install ReportGenerator Global Tool
  inputs:
      command: custom
      custom: tool
      arguments: install dotnet-reportgenerator-globaltool -g

- script: 
    echo "##vso[task.prependpath]$HOME/.dotnet/tools"

- script: 
    reportgenerator -reports:$(Build.SourcesDirectory)/CodeCoverage/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage "-reporttypes:HtmlInline_AzurePipelines;Cobertura"

- task: PublishCodeCoverageResults@1
  inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/coverage.cobertura.xml'
      reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
      failIfCoverageEmpty: true